import type { Restaurant } from "./types";

/**
 * 50 highly-rated restaurants across the greater Seattle area,
 * sourced from OpenTable, Resy, Eater Seattle, and Seattle Met (2025–2026).
 * Google ratings and menu links included.
 */
export const SEED_RESTAURANTS: Omit<Restaurant, "id" | "addedAt" | "visited" | "votes">[] = [
  {
    name: "Café Juanita",
    cuisine: "Italian",
    neighborhood: "Kirkland",
    address: "9702 NE 120th Pl, Kirkland, WA 98034",
    priceRange: 4,
    notes: "James Beard Award-winning Northern Italian. Seasonal tasting menus, house-made pastas, and an award-winning wine list. Set beside Juanita Creek.",
    addedBy: "Friday Feast",
    website: "https://cafejuanita.com",
    menuUrl: "https://www.cafejuanita.com/menu",
    googleRating: 4.6,
    latitude: 47.7154,
    longitude: -122.1942,
  },
  {
    name: "The Pink Door",
    cuisine: "Italian",
    neighborhood: "Belltown",
    address: "1919 Post Alley, Seattle, WA 98101",
    priceRange: 3,
    notes: "Iconic unmarked entrance off Post Alley. House-made pasta, live cabaret, trapeze, and sweeping Elliott Bay views. Since 1981.",
    addedBy: "Friday Feast",
    website: "https://thepinkdoor.net",
    menuUrl: "https://www.thepinkdoor.net/menus/",
    googleRating: 4.6,
    latitude: 47.6101,
    longitude: -122.3426,
  },
  {
    name: "Sushi Kashiba",
    cuisine: "Japanese",
    neighborhood: "Pike Place Market",
    address: "86 Pine St, Seattle, WA 98101",
    priceRange: 4,
    notes: "Master sushi chef Shiro Kashiba trained under Jiro Ono. Edomae-style nigiri, seasonal omakase at Pike Place Market.",
    addedBy: "Friday Feast",
    website: "https://sushikashiba.com",
    menuUrl: "https://sushikashiba.com/menu",
    googleRating: 4.7,
    latitude: 47.6103,
    longitude: -122.3406,
  },
  {
    name: "Atoma",
    cuisine: "American",
    neighborhood: "Wallingford",
    address: "1411 N 45th St, Seattle, WA 98103",
    priceRange: 4,
    notes: "Esquire's Best New Restaurant in America 2024. Canlis alumnus Johnny Courtney's hyper-seasonal PNW tasting menu in a Wallingford Craftsman.",
    addedBy: "Friday Feast",
    website: "https://www.atomaseattle.com",
    menuUrl: "https://www.atomaseattle.com",
    googleRating: 4.8,
    latitude: 47.6613,
    longitude: -122.3398,
  },
  {
    name: "COMMUNION",
    cuisine: "American",
    neighborhood: "Central District",
    address: "2310 E Union St, Seattle, WA 98122",
    priceRange: 3,
    notes: "Chef Kristi Brown's 'Seattle Soul' — Southern staples woven with Asian, Filipino, and East African influences. Condé Nast Traveller top 12 worldwide.",
    addedBy: "Friday Feast",
    website: "https://www.communionseattle.com",
    menuUrl: "https://www.communionseattle.com/menu",
    googleRating: 4.7,
    latitude: 47.6125,
    longitude: -122.2956,
  },
  {
    name: "Lark",
    cuisine: "American",
    neighborhood: "Capitol Hill",
    address: "952 E Seneca St, Seattle, WA 98122",
    priceRange: 3,
    notes: "Capitol Hill stalwart since 2003. Seasonal shared plates, charcuterie, and one of the city's finest wine lists. James Beard semifinalist.",
    addedBy: "Friday Feast",
    website: "https://larkseattle.com",
    menuUrl: "https://larkseattle.com/menu/",
    googleRating: 4.5,
    latitude: 47.6091,
    longitude: -122.3193,
  },
  {
    name: "Palace Kitchen",
    cuisine: "American",
    neighborhood: "Belltown",
    address: "2030 5th Ave, Seattle, WA 98121",
    priceRange: 3,
    notes: "Tom Douglas's beloved Belltown kitchen since 1996. Wood-fired rotisserie, late-night menu, and one of the best burgers in Seattle.",
    addedBy: "Friday Feast",
    website: "https://tomdouglas.com/restaurants/palace-kitchen",
    menuUrl: "https://tomdouglas.com/restaurants/palace-kitchen",
    googleRating: 4.5,
    latitude: 47.6137,
    longitude: -122.3437,
  },
  {
    name: "Musang",
    cuisine: "Other",
    neighborhood: "Beacon Hill",
    address: "2524 Beacon Ave S, Seattle, WA 98144",
    priceRange: 3,
    notes: "James Beard-nominated Filipino. Chef Melissa Miranda pairs PNW produce with family recipes — kare-kare, fried chicken, pork lumpia.",
    addedBy: "Friday Feast",
    website: "https://www.musangseattle.com",
    menuUrl: "https://www.musangseattle.com/menu",
    googleRating: 4.5,
    latitude: 47.5817,
    longitude: -122.3132,
  },
  {
    name: "Joule",
    cuisine: "Korean",
    neighborhood: "Wallingford",
    address: "1913 N 45th St, Seattle, WA 98103",
    priceRange: 3,
    notes: "Four-time James Beard-nominated Korean steakhouse. Kalbi short rib, wagyu, rice cakes with chorizo. Bon Appétit Best New Restaurant.",
    addedBy: "Friday Feast",
    website: "https://joulerestaurant.com",
    menuUrl: "https://joulerestaurant.com/menu",
    googleRating: 4.4,
    latitude: 47.6614,
    longitude: -122.3340,
  },
  {
    name: "TOMO",
    cuisine: "Japanese",
    neighborhood: "White Center",
    address: "9908 16th Ave SW, Seattle, WA 98106",
    priceRange: 4,
    notes: "28-seat White Center prix-fixe from former Canlis chef Brady Williams. Plant-forward tasting menu. 15,000-person waitlist before opening.",
    addedBy: "Friday Feast",
    website: "https://www.tomorestaurant.com",
    menuUrl: "https://tomoseattle.com",
    googleRating: 4.1,
    latitude: 47.5173,
    longitude: -122.3534,
  },
  {
    name: "The Corson Building",
    cuisine: "American",
    neighborhood: "Georgetown",
    address: "5609 Corson Ave S, Seattle, WA 98108",
    priceRange: 4,
    notes: "Chef Emily Crawford Dann's hyper-seasonal PNW prix fixe in a lantern-lit Georgetown garden. Sunday Supper is a highlight.",
    addedBy: "Friday Feast",
    website: "https://www.thecorsonbuilding.com",
    menuUrl: "https://www.thecorsonbuilding.com",
    googleRating: 4.6,
    latitude: 47.5531,
    longitude: -122.3227,
  },
  {
    name: "El Camino",
    cuisine: "Mexican",
    neighborhood: "Fremont",
    address: "607 N 35th St, Seattle, WA 98103",
    priceRange: 2,
    notes: "Nearly 30 years in Fremont. Chef Arturo Perez's Michoacán roots — enchiladas with mole coloradito, salmon con tamarindo. Daily happy hour.",
    addedBy: "Friday Feast",
    website: "https://elcaminorestaurant.com",
    menuUrl: "https://elcaminorestaurant.com/menu/",
    googleRating: 4.5,
    latitude: 47.6506,
    longitude: -122.3502,
  },
  {
    name: "Fuji Sushi",
    cuisine: "Japanese",
    neighborhood: "Chinatown-ID",
    address: "520 S Main St, Seattle, WA 98104",
    priceRange: 2,
    notes: "Precise nigiri, tatami rooms, and one of the city's best sushi values. Super deluxe chef's selection — 12 pieces plus roll for $55.",
    addedBy: "Friday Feast",
    website: "https://www.fujisushiseattle.com",
    menuUrl: "https://www.fujisushiseattle.com/menu",
    googleRating: 4.3,
    latitude: 47.5990,
    longitude: -122.3280,
  },
  {
    name: "SWeL Restaurant",
    cuisine: "American",
    neighborhood: "Fremont",
    address: "3601 Fremont Ave N #100, Seattle, WA 98103",
    priceRange: 2,
    notes: "Fremont hideaway with wood-fired scallops, pear-Gorgonzola pizza, and a killer tequila old fashioned. Great date spot.",
    addedBy: "Friday Feast",
    googleRating: 4.5,
    latitude: 47.6520,
    longitude: -122.3499,
  },
  {
    name: "Noodle/Bar",
    cuisine: "Chinese",
    neighborhood: "South Lake Union",
    address: "220 Yale Ave N, Seattle, WA 98109",
    priceRange: 1,
    notes: "Hand-pulled Washington wheat noodles. The beef meatball noodle with wood-ear mushrooms and chile oil is rainy-day therapy.",
    addedBy: "Friday Feast",
    menuUrl: "https://www.noodlebarseattle.com",
    googleRating: 4.5,
    latitude: 47.6210,
    longitude: -122.3298,
  },
  {
    name: "Zig Zag Café",
    cuisine: "American",
    neighborhood: "Pike Place Market",
    address: "1501 Western Ave #202, Seattle, WA 98101",
    priceRange: 2,
    notes: "Legendary speakeasy below Pike Place since 1999. Craft cocktails, live jazz, duck fat popcorn. Home of the Last Word cocktail revival.",
    addedBy: "Friday Feast",
    website: "https://zigzagseattle.com",
    menuUrl: "https://zigzagseattle.com/food-menu/",
    googleRating: 4.5,
    latitude: 47.6090,
    longitude: -122.3420,
  },
  {
    name: "Happy Crab",
    cuisine: "Seafood",
    neighborhood: "Ballard",
    address: "6135 Seaview Ave NW, Seattle, WA 98107",
    priceRange: 2,
    notes: "13,000 sq ft Ballard spot with panoramic water views. Cajun-Asian seafood boils, black truffle xiao long bao, and robot runners.",
    addedBy: "Friday Feast",
    website: "https://www.happycrab.com",
    menuUrl: "https://www.happycrab.com/menu",
    googleRating: 4.3,
    latitude: 47.6691,
    longitude: -122.4030,
  },
  {
    name: "MEET Korean BBQ",
    cuisine: "Korean",
    neighborhood: "Capitol Hill",
    address: "500 E Pike St, Seattle, WA 98122",
    priceRange: 2,
    notes: "Tabletop grilling on Capitol Hill — wagyu, prime Angus, kurobuta pork. The Signature Feast with kimchi, corn cheese, and egg soufflé.",
    addedBy: "Friday Feast",
    website: "https://www.meetkoreanbbq.com",
    menuUrl: "https://www.meetkoreanbbq.com/menu",
    googleRating: 4.5,
    latitude: 47.6143,
    longitude: -122.3261,
  },
  {
    name: "Canlis",
    cuisine: "American",
    neighborhood: "Queen Anne",
    address: "2576 Aurora Ave N, Seattle, WA 98109",
    priceRange: 4,
    notes: "75 years of iconic Northwest fine dining. $180 tasting menu, tableside Canlis salad, mid-century design, and lake views. Dress sharp.",
    addedBy: "Friday Feast",
    website: "https://canlis.com",
    menuUrl: "https://canlis.com/menus/",
    googleRating: 4.6,
    latitude: 47.6430,
    longitude: -122.3471,
  },
  {
    name: "Ray's Café",
    cuisine: "Seafood",
    neighborhood: "Ballard",
    address: "6049 Seaview Ave NW, Seattle, WA 98107",
    priceRange: 3,
    notes: "50-year Ballard icon. Dungeness crab dip, sablefish in sake kasu, and Olympic Mountain sunsets. Extensive wine list.",
    addedBy: "Friday Feast",
    website: "https://www.rays.com",
    menuUrl: "https://www.rays.com/menu/",
    googleRating: 4.3,
    latitude: 47.6680,
    longitude: -122.4024,
  },
  {
    name: "Maximilien",
    cuisine: "French",
    neighborhood: "Pike Place Market",
    address: "81A Pike St, Seattle, WA 98101",
    priceRange: 3,
    notes: "Classic French bistro perched above Pike Place Market. Plateau de Fruits de Mer, steak frites, and Elliott Bay views from igloos in winter.",
    addedBy: "Friday Feast",
    website: "https://maximilienrestaurant.com",
    menuUrl: "https://maximilienrestaurant.com/menu/",
    googleRating: 4.5,
    latitude: 47.6098,
    longitude: -122.3410,
  },
  {
    name: "Delish Ethiopian Cuisine",
    cuisine: "Ethiopian",
    neighborhood: "Hillman City",
    address: "4816 Rainier Ave S, Seattle, WA 98118",
    priceRange: 1,
    notes: "Pillowy injera with scoopable kitfo and spicy misir wot. Sizzling tibs are a must. Generous veggie and meat combos.",
    addedBy: "Friday Feast",
    googleRating: 4.8,
    latitude: 47.5573,
    longitude: -122.2896,
  },
  {
    name: "Qiao Lin Hotpot",
    cuisine: "Chinese",
    neighborhood: "Downtown",
    address: "1424 4th Ave, Seattle, WA 98101",
    priceRange: 2,
    notes: "Chongqing-style hot pot downtown. A5 wagyu, meticulous knife work, customizable spicy base. Gold cow sculptures deliver your food.",
    addedBy: "Friday Feast",
    website: "https://www.qiaolinhotpot.com",
    menuUrl: "https://www.qiaolinhotpot.com/menu",
    googleRating: 4.6,
    latitude: 47.6097,
    longitude: -122.3365,
  },
  {
    name: "Sacro Bosco",
    cuisine: "Pizza",
    neighborhood: "Central District",
    address: "1501 Pike Pl #321, Seattle, WA 98101",
    priceRange: 2,
    notes: "Roman-style sourdough pizza from the Temple Pastries team. Salame piccante with Calabrian chile. Excellent tiramisu.",
    addedBy: "Friday Feast",
    googleRating: 4.6,
    latitude: 47.6100,
    longitude: -122.3118,
  },
  {
    name: "Majnoon",
    cuisine: "Middle Eastern",
    neighborhood: "Pioneer Square",
    address: "722 1st Ave S, Seattle, WA 98104",
    priceRange: 2,
    notes: "Persian poetry-inspired cocktail bar in Pioneer Square. Saffron, mezcal, pomegranate cocktails. Rotating gallery art and 5-6pm happy hour.",
    addedBy: "Friday Feast",
    website: "https://www.majnoonsea.com",
    menuUrl: "https://www.majnoonsea.com/cocktail-menu",
    googleRating: 4.5,
    latitude: 47.5987,
    longitude: -122.3344,
  },
  {
    name: "Archipelago",
    cuisine: "American",
    neighborhood: "Rainier Valley",
    address: "5607 Rainier Ave S, Seattle, WA 98118",
    priceRange: 4,
    notes: "Intimate Rainier Valley fine dining with an ever-changing tasting menu. PNW ingredients in inventive preparations. James Beard-nominated.",
    addedBy: "Friday Feast",
    googleRating: 4.6,
    latitude: 47.5530,
    longitude: -122.2870,
  },
  {
    name: "wa'z Seattle",
    cuisine: "Japanese",
    neighborhood: "Belltown",
    address: "2000 2nd Ave, Seattle, WA 98121",
    priceRange: 4,
    notes: "Kaiseki-style Japanese fine dining in Belltown. Multi-course seasonal menus with artful presentation.",
    addedBy: "Friday Feast",
    googleRating: 4.5,
    latitude: 47.6136,
    longitude: -122.3450,
  },
  {
    name: "The Herbfarm",
    cuisine: "American",
    neighborhood: "Woodinville",
    address: "14590 NE 145th St, Woodinville, WA 98072",
    priceRange: 4,
    notes: "Legendary Northwest destination. Nine-course themed dinners paired with five wines from their own garden. AAA 5 Diamond.",
    addedBy: "Friday Feast",
    website: "https://www.theherbfarm.com",
    menuUrl: "https://herbfarm.com/dinner-information/",
    googleRating: 4.8,
    latitude: 47.7330,
    longitude: -122.1443,
  },
  {
    name: "Altura",
    cuisine: "Italian",
    neighborhood: "Capitol Hill",
    address: "617 Broadway E, Seattle, WA 98102",
    priceRange: 4,
    notes: "Capitol Hill Italian tasting menu. Refined seasonal courses, house-made pasta, and exceptional wine. Opinionated About Dining top 250.",
    addedBy: "Friday Feast",
    website: "https://alturarestaurant.com",
    menuUrl: "https://alturarestaurant.com/menus/",
    googleRating: 4.7,
    latitude: 47.6249,
    longitude: -122.3208,
  },
  {
    name: "Homer",
    cuisine: "Mediterranean",
    neighborhood: "Beacon Hill",
    address: "3013 Beacon Ave S, Seattle, WA 98144",
    priceRange: 3,
    notes: "Beacon Hill gem. Middle Eastern-Mediterranean flavors from chef James Snyder. Wood-fired dishes, seasonal menu.",
    addedBy: "Friday Feast",
    googleRating: 4.6,
    latitude: 47.5757,
    longitude: -122.3132,
  },
  {
    name: "Nishino",
    cuisine: "Japanese",
    neighborhood: "Madison Park",
    address: "3130 E Madison St, Seattle, WA 98112",
    priceRange: 3,
    notes: "Madison Park Japanese fine dining. Pristine sushi, kaiseki-influenced dishes. A Seattle institution for over two decades.",
    addedBy: "Friday Feast",
    website: "https://nishinorestaurant.com",
    menuUrl: "https://nishinorestaurant.com/menu/",
    googleRating: 4.6,
    latitude: 47.6326,
    longitude: -122.2866,
  },
  {
    name: "Aroy Mak Thai",
    cuisine: "Thai",
    neighborhood: "Capitol Hill",
    address: "1423 12th Ave, Seattle, WA 98122",
    priceRange: 1,
    notes: "Yelp top-100 US restaurant. Authentic Thai on Capitol Hill — bold curries, fresh papaya salad, and incredible pad kra pao.",
    addedBy: "Friday Feast",
    googleRating: 4.7,
    latitude: 47.6137,
    longitude: -122.3162,
  },
  {
    name: "Von's 1000 Spirits",
    cuisine: "American",
    neighborhood: "Woodinville",
    address: "14450 Woodinville-Redmond Rd NE, Woodinville, WA 98072",
    priceRange: 2,
    notes: "Yelp top-100 US restaurant. 1,000+ spirits, seasonal American fare alongside the wine country tasting rooms.",
    addedBy: "Friday Feast",
    googleRating: 4.5,
    latitude: 47.7314,
    longitude: -122.1426,
  },
  {
    name: "Ascend Prime Steak & Sushi",
    cuisine: "Japanese",
    neighborhood: "Bellevue",
    address: "10400 NE 4th St Floor 31, Bellevue, WA 98004",
    priceRange: 4,
    notes: "31st-floor steak-meets-sushi with panoramic Bellevue views. Luxe crudos, prime steaks, and a traditional sushi bar.",
    addedBy: "Friday Feast",
    website: "https://ascendprime.com",
    menuUrl: "https://ascendprime.com/menu/",
    googleRating: 4.3,
    latitude: 47.6151,
    longitude: -122.2026,
  },
  {
    name: "El Gaucho Bellevue",
    cuisine: "American",
    neighborhood: "Bellevue",
    address: "450 108th Ave NE, Bellevue, WA 98004",
    priceRange: 4,
    notes: "Iconic steakhouse since 1953. Tableside Caesar salad, 28-day dry-aged steaks, flambéed Bananas Foster.",
    addedBy: "Friday Feast",
    website: "https://elgaucho.com",
    menuUrl: "https://elgaucho.com/menus/",
    googleRating: 4.5,
    latitude: 47.6164,
    longitude: -122.1963,
  },
  {
    name: "Cantinetta Bellevue",
    cuisine: "Italian",
    neighborhood: "Bellevue",
    address: "10038 Main St, Bellevue, WA 98004",
    priceRange: 3,
    notes: "Authentic Tuscan cuisine in Old Bellevue. Handmade pasta, seasonal ingredients, and Italian wines.",
    addedBy: "Friday Feast",
    website: "https://cantinettabellevue.com",
    menuUrl: "https://cantinettabellevue.com/menu/",
    googleRating: 4.4,
    latitude: 47.6153,
    longitude: -122.2038,
  },
  {
    name: "Monsoon Bellevue",
    cuisine: "Vietnamese",
    neighborhood: "Bellevue",
    address: "10245 Main St, Bellevue, WA 98004",
    priceRange: 2,
    notes: "Modern Vietnamese fusion. Catfish claypot, grilled pork belly, and creative cocktails. Sister restaurant to the Capitol Hill original.",
    addedBy: "Friday Feast",
    menuUrl: "https://www.monsoonrestaurants.com/bellevue-menu",
    googleRating: 4.3,
    latitude: 47.6152,
    longitude: -122.2043,
  },
  {
    name: "Din Tai Fung",
    cuisine: "Chinese",
    neighborhood: "University District",
    address: "2621 NE 46th St, Seattle, WA 98105",
    priceRange: 2,
    notes: "Legendary Taiwanese soup dumplings (xiao long bao). Consistently packed University Village location. Also in Bellevue.",
    addedBy: "Friday Feast",
    website: "https://dintaifungusa.com",
    menuUrl: "https://dintaifungusa.com/us/menu.html",
    googleRating: 4.4,
    latitude: 47.6619,
    longitude: -122.2998,
  },
  {
    name: "Serious Pie",
    cuisine: "Pizza",
    neighborhood: "South Lake Union",
    address: "401 Westlake Ave N, Seattle, WA 98109",
    priceRange: 2,
    notes: "Tom Douglas's artisan wood-fired pizzas. Chanterelle, truffle cheese, and roasted pepper topping combos.",
    addedBy: "Friday Feast",
    website: "https://tomdouglas.com/restaurants/serious-pie",
    menuUrl: "https://tomdouglas.com/restaurants/serious-pie",
    googleRating: 4.3,
    latitude: 47.6225,
    longitude: -122.3377,
  },
  {
    name: "Shiro's Sushi",
    cuisine: "Japanese",
    neighborhood: "Belltown",
    address: "2401 2nd Ave, Seattle, WA 98121",
    priceRange: 3,
    notes: "Belltown's omakase legacy founded by Shiro Kashiba. Pristine nigiri, intimate counter seating, seasonal Pacific NW seafood.",
    addedBy: "Friday Feast",
    website: "https://shiros.com",
    menuUrl: "https://shiros.com/menu/",
    googleRating: 4.5,
    latitude: 47.6156,
    longitude: -122.3470,
  },
  {
    name: "Kedai Makan",
    cuisine: "Thai",
    neighborhood: "Capitol Hill",
    address: "1802 Bellevue Ave, Seattle, WA 98122",
    priceRange: 1,
    notes: "Malaysian-inspired street food on Capitol Hill. Nasi lemak, roti canai, laksa, and charcoal-grilled satay.",
    addedBy: "Friday Feast",
    googleRating: 4.5,
    latitude: 47.6157,
    longitude: -122.3253,
  },
  {
    name: "Spinasse",
    cuisine: "Italian",
    neighborhood: "Capitol Hill",
    address: "1531 14th Ave, Seattle, WA 98122",
    priceRange: 3,
    notes: "Piedmontese Italian on Capitol Hill. Hand-rolled tajarin pasta is legendary. Cozy, romantic, and always excellent.",
    addedBy: "Friday Feast",
    website: "https://spinasse.com",
    menuUrl: "https://spinasse.com/menus/",
    googleRating: 4.6,
    latitude: 47.6148,
    longitude: -122.3144,
  },
  {
    name: "Toulouse Petit",
    cuisine: "Other",
    neighborhood: "Queen Anne",
    address: "601 Queen Anne Ave N, Seattle, WA 98109",
    priceRange: 2,
    notes: "Cajun-Creole brunch-through-dinner on Queen Anne. Beignets, crawfish étouffée, and a 5-hour daily happy hour.",
    addedBy: "Friday Feast",
    website: "https://toulousepetit.com",
    menuUrl: "https://toulousepetit.com/menu/",
    googleRating: 4.3,
    latitude: 47.6245,
    longitude: -122.3567,
  },
  {
    name: "Matt's in the Market",
    cuisine: "Seafood",
    neighborhood: "Pike Place Market",
    address: "94 Pike St #32, Seattle, WA 98101",
    priceRange: 3,
    notes: "Tiny gem above Pike Place Market. Seasonal seafood and PNW ingredients sourced steps away. Phenomenal cataplana.",
    addedBy: "Friday Feast",
    website: "https://mattsinthemarket.com",
    menuUrl: "https://mattsinthemarket.com/menu/",
    googleRating: 4.5,
    latitude: 47.6094,
    longitude: -122.3405,
  },
  {
    name: "Ba Bar",
    cuisine: "Vietnamese",
    neighborhood: "Capitol Hill",
    address: "550 12th Ave, Seattle, WA 98122",
    priceRange: 1,
    notes: "Capitol Hill Vietnamese — steaming pho, crispy banh mi, and strong Vietnamese iced coffee. Lively and affordable.",
    addedBy: "Friday Feast",
    website: "https://babarseattle.com",
    menuUrl: "https://babarseattle.com/menu/",
    googleRating: 4.3,
    latitude: 47.6136,
    longitude: -122.3162,
  },
  {
    name: "Stateside",
    cuisine: "Vietnamese",
    neighborhood: "Capitol Hill",
    address: "300 E Pike St, Seattle, WA 98122",
    priceRange: 2,
    notes: "Refined French-Vietnamese on Capitol Hill. Beautifully plated, creative cocktails, and a stylish dining room.",
    addedBy: "Friday Feast",
    googleRating: 4.4,
    latitude: 47.6143,
    longitude: -122.3279,
  },
  {
    name: "Brimmer & Heeltap",
    cuisine: "American",
    neighborhood: "Ballard",
    address: "425 NW Market St, Seattle, WA 98107",
    priceRange: 2,
    notes: "Neighborhood Ballard gem. Seasonal New American with craft cocktails. Warm, inviting, and always consistent.",
    addedBy: "Friday Feast",
    googleRating: 4.5,
    latitude: 47.6688,
    longitude: -122.3754,
  },
  {
    name: "Revel",
    cuisine: "Korean",
    neighborhood: "Fremont",
    address: "403 N 36th St, Seattle, WA 98103",
    priceRange: 2,
    notes: "Rachel Yang's Korean-French fusion in Fremont. Rice-bowl-meets-fine-dining. Pancetta-kimchi fried rice and dumplings.",
    addedBy: "Friday Feast",
    googleRating: 4.4,
    latitude: 47.6515,
    longitude: -122.3511,
  },
  {
    name: "Carmine's Bellevue",
    cuisine: "Italian",
    neighborhood: "Bellevue",
    address: "88 102nd Ave NE, Bellevue, WA 98004",
    priceRange: 3,
    notes: "Old-school Italian. Veal scaloppine, rigatoni bolognese, and upscale service in a classic dining room.",
    addedBy: "Friday Feast",
    googleRating: 4.3,
    latitude: 47.6164,
    longitude: -122.1978,
  },
  {
    name: "Duke's Seafood Tacoma",
    cuisine: "Seafood",
    neighborhood: "Tacoma",
    address: "751 Pacific Ave, Tacoma, WA 98402",
    priceRange: 2,
    notes: "Waterfront dining in Tacoma. Wild-caught Pacific seafood, award-winning chowder, and fish tacos.",
    addedBy: "Friday Feast",
    website: "https://dukesseafood.com",
    menuUrl: "https://dukesseafood.com/menu/",
    googleRating: 4.3,
    latitude: 47.2529,
    longitude: -122.4381,
  },
  {
    name: "En Rama",
    cuisine: "Mediterranean",
    neighborhood: "Tacoma",
    address: "818 Division Ave, Tacoma, WA 98403",
    priceRange: 2,
    notes: "Chef-driven plates in a stylish Tacoma setting. Seasonal Mediterranean-inspired menu with natural wines.",
    addedBy: "Friday Feast",
    googleRating: 4.5,
    latitude: 47.2577,
    longitude: -122.4501,
  },
];
